### ISSUE TITLE
Due to overly strict limitations, some requests with a content-type of CBOR were not  intercepted.

### ISSUE THREAD

**Issue by ljx1990** [jorgenbuilder/ic-inspector#33]
ic-inspector has indeed provided great help in the development of IC, but I have encountered an issue. When the content-type is already application/cbor and the message body content is also in cbor format, some cbor content is not properly captured due to the following code limitations:

export function shouldCapture(event: chrome.devtools.network.Request): boolean {
return (
isBoundaryNodeURL(event.request.url) && event.request.method === 'POST'
(isBoundaryNodeURL(event.request.url) || hasICHeaders(event)) &&
event.request.method === 'POST'
);
}

Can we relax the code to only check the content-type and body content?

**Comment by jorgenbuilder** [comment]
Yes, I think we could potentially relax to contentType=cbor as the only requirement. Would you be interested in creating a PR @ljx199?

**Comment by jorgenbuilder** [comment]
This has been rolled out.
