### ISSUE TITLE
When the requested content-type is text, but the returned type is cbor, it cannot be captured

### ISSUE THREAD

**Issue by ljx1990** [jorgenbuilder/ic-inspector#34]
When the requested content-type is text, but the returned type is cbor, it cannot be captured. This is because only the parsing of requests and responses with cbor types is implemented in the code. Let's see how to support this.
![image](https://user-images.githubusercontent.com/7532701/227823085-1922cd43-01c3-4e62-b961-99bf10e17ac7.png)

**Comment by jorgenbuilder** [comment]
In what cases would `content-type` be text?

**Comment by ljx1990** [comment]
in "status" case  request is text  ,but the response is cbor

**Comment by jorgenbuilder** [comment]
Ah, I understand what you mean by this (finally 😆)

```
/**
 * Determines whether the request uses a cbor content type.
 */
export function isCBOR(event: chrome.devtools.network.Request): boolean {
    return event.request.headers.some(
        (h) => h.name === 'content-type' && h.value.includes('cbor'),
    );
}
```

The selection code above only works when the request uses cbor. I'll look into it.

**Comment by jorgenbuilder** [comment]
Latest version inspects response headers instead of request headers. Works well in my local testing so far, let's see how it does in production.
