### ISSUE TITLE
Values displayed in IC Inspector do not match actual values

### ISSUE THREAD

**Issue by hewm** [jorgenbuilder/ic-inspector#38]
NNS 
![image](https://github.com/jorgenbuilder/ic-inspector/assets/20858116/49846b74-2852-4309-a0f7-f581591c7f78)
The actual **memo** value of the front end is **12070089694624444626**
![image](https://github.com/jorgenbuilder/ic-inspector/assets/20858116/7bfb662e-b7c3-40a0-aa89-42c9f324d716)
The **memo** value displayed by IC Inspector is **12070089694624444000**

**Comment by jorgenbuilder** [comment]
Fixed in commit https://github.com/jorgenbuilder/ic-inspector/commit/998b74508e23232b8df73e24a9958bfc39d02327. New release v1.1.5 is pending on the chrome store.

**Comment by hewm** [comment]
![image](https://github.com/jorgenbuilder/ic-inspector/assets/20858116/9aad2b70-5c6f-45f7-b25f-c5526a2bf7ca)
**I hope the font display can be optimized😂😂😂😂😂😂**
![image](https://github.com/jorgenbuilder/ic-inspector/assets/20858116/51d42ba4-9455-42cf-b41f-26904d6d805e)
**In the interface that owns the did file it also shows**
`Could not determine candid interface for this canister, so this is a partial decode.`

**Comment by hewm** [comment]
In terms of fonts, I just personally think that the previous version looks more comfortable 😂
![image](https://github.com/jorgenbuilder/ic-inspector/assets/20858116/068929d0-f98c-4549-9b60-e06d4f5bac37)

**new suggestions**
1、It seems better if you can add a button to copy the response with one click；
2、Really display the response value as a standard Json format and convert it, such as 185581n, to 185581, so that the result can be copied directly for use 😅
